services:
  thunderbirdsboardgameengine.gamedata.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Cors__AllowedOrigins: http://localhost:3000
    ports:
      - "8000:80"
    volumes:
      - ./TestData:/app/TestData