namespace ThunderbirdsBoardGameEngine.PublishedLanguage.DisasterBonus
{
    /// <summary>
    /// Opaque, globally unique bonus identifier.
    /// Generated by the Catalog context.
    /// Format is implementation detail — do not parse.
    /// </summary>
    [Obsolete("Published language is deprecated. Use Reference Data instead")]
    public readonly record struct DisasterBonusKey
    {
        /// <summary>
        /// Gets the value represented by this instance.
        /// </summary>
        public string Value { get; }

        /// <summary>
        /// Initializes a new instance of the DisasterBonusKey class with the specified string value.
        /// </summary>
        /// <param name="value">The string value to assign to the key. Cannot be null.</param>
        public DisasterBonusKey(string value)
        {
            Value = value;
        }

        /// <summary>
        /// Returns the string representation of the current object.
        /// </summary>
        /// <returns>A string that represents the value of the current object.</returns>
        public override string ToString()
        {
            return Value;
        }
    }
}
