namespace ThunderbirdsBoardGameEngine.PublishedLanguage.DisasterBonus
{
    /// <summary>
    /// Opaque, globally unique bonus identifier.
    /// Generated by the Catalog context.
    /// Format is implementation detail — do not parse.
    /// </summary>
    public readonly record struct DisasterBonusKey(string Value);
}
