services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      Catalog__DisasterCards__Json__FilePath: /app/TestData/Catalog/DisasterCards/Enveloped/disaster-cards.json     
    volumes:
      - ../TestData:/app/TestData
    ports:
      - "8080:8080"   # publish so the host (runner) can call localhost:8080
