<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\tools\Common\ThunderbirdsBoardGameEngine.WireMock.Hosting\ThunderbirdsBoardGameEngine.WireMock.Hosting.csproj" />
  </ItemGroup>

</Project>
