// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThunderbirdsBoardGameEngine.GameState.Infrastructure.Persistence;

#nullable disable

namespace ThunderbirdsBoardGameEngine.GameState.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameStateDbContext))]
    [Migration("20260727151008_InitialGameState")]
    partial class InitialGameState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThunderbirdsBoardGameEngine.GameState.Infrastructure.Persistence.Records.CharacterStateRecord", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ThunderbirdCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("GameId", "CharacterCode");

                    b.ToTable("game_character_assignments", (string)null);
                });

            modelBuilder.Entity("ThunderbirdsBoardGameEngine.GameState.Infrastructure.Persistence.Records.GameRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SetupVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("ThunderbirdsBoardGameEngine.GameState.Infrastructure.Persistence.Records.ThunderbirdMachineStateRecord", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThunderbirdCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("GameId", "ThunderbirdCode");

                    b.ToTable("game_machine_positions", (string)null);
                });

            modelBuilder.Entity("ThunderbirdsBoardGameEngine.GameState.Infrastructure.Persistence.Records.CharacterStateRecord", b =>
                {
                    b.HasOne("ThunderbirdsBoardGameEngine.GameState.Infrastructure.Persistence.Records.GameRecord", "Game")
                        .WithMany("CharacterStates")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ThunderbirdsBoardGameEngine.GameState.Infrastructure.Persistence.Records.ThunderbirdMachineStateRecord", b =>
                {
                    b.HasOne("ThunderbirdsBoardGameEngine.GameState.Infrastructure.Persistence.Records.GameRecord", "Game")
                        .WithMany("ThunderbirdMachineStates")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ThunderbirdsBoardGameEngine.GameState.Infrastructure.Persistence.Records.GameRecord", b =>
                {
                    b.Navigation("CharacterStates");

                    b.Navigation("ThunderbirdMachineStates");
                });
#pragma warning restore 612, 618
        }
    }
}
