name: Build (reusable)

on:
  workflow_call:
    inputs:
      solution_file:
        required: true
        type: string

jobs:
  build:
    name: Build .NET Solution
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.x'

      - uses: ./.github/actions/authenticate-github-packages
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore & Build
        run: |
          dotnet restore "${{ inputs.solution_file }}"
          dotnet build "${{ inputs.solution_file }}" --configuration Release --no-restore
