name: Build (reusable)

on:
  workflow_call:
    inputs:
      solution_file:
        required: true
        type: string

jobs:
  build:
    name: Build .NET Solution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore & Build
        run: |
          dotnet restore "${{ inputs.solution_file }}"
          dotnet build "${{ inputs.solution_file }}" --configuration Release --no-restore

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t thunderbirds-api -f ThunderbirdsBoardGameEngine.Api/Dockerfile .

      - name: Save Docker Image
        run: docker save thunderbirds-api -o thunderbirds-api.tar
      
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderbirds-api-image
          path: thunderbirds-api.tar
          retention-days: 7
      