name: CI - Main

on:
  push:
    branches: 
        - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: read

env:
  SOLUTION_FILE: &solution ThunderbirdsBoardGameEngine.sln
  BASE_URL: &base_url "http://localhost:8080"

jobs:
  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      solution_file: *solution

  build:
    uses: ./.github/workflows/build.yml
    with:
      solution_file: *solution
      docker_build: true
    needs:
      - static-analysis

  tests:
    uses: ./.github/workflows/tests.yml
    with:
      solution_file: *solution
      run_component: true
      run_integration: true
      run_playwright: true
      base_url: *base_url
    needs:
      - build

  compute-version:
    uses: ./.github/workflows/version.yml
    with:
      pr_title: ${{ github.event.pull_request.title || github.event.head_commit.message }}
    needs:
      - tests

  tag-repo:
    uses: ./.github/workflows/tag-repo.yml
    with:
      version: ${{ needs.compute-version.outputs.version }}
      tag_prefix: "server/v"
    needs:
      - compute-version

  docker_publish:
    uses: ./.github/workflows/publish-docker.yml
    with:
      image_name: thunderbirds-api
      version: ${{ needs.compute_version.outputs.version }}
      push_latest: ${{ github.ref == 'refs/heads/main' }}
    secrets:
      registry_token: ${{ secrets.GITHUB_TOKEN }}
    needs:
      - compute-version