name: CI - Main

on:
  push:
    branches: 
        - main

env:
  SOLUTION_FILE: &solution ThunderbirdsBoardGameEngine.sln

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      solution_file: *solution
      docker_build: true

  tests:
    uses: ./.github/workflows/tests.yml
    with:
      solution_file: *solution
      run_unit: true
      run_component: true
      run_integration: true
      run_playwright: true
    needs:
      - build
