name: CI - Main

on:
  push:
    branches: 
        - main

env:
  SOLUTION_FILE: &solution ThunderbirdsBoardGameEngine.sln

jobs:
  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      solution_file: *solution

  build:
    uses: ./.github/workflows/build.yml
    with:
      solution_file: *solution
      docker_build: true
    needs:
      - static-analysis

  docker-env:
    uses: ./.github/workflows/docker-env.yml
    needs: 
      - build

  tests:
    uses: ./.github/workflows/tests.yml
    with:
      solution_file: *solution
      run_component: true
      run_integration: true
      run_playwright: true
    needs:
      - docker-env
    
  teardown:
    uses: ./.github/workflows/docker-teardown.yml
    needs: 
      - tests