name: CI - PR/Branch

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

env:
  SOLUTION_FILE: &solution ThunderbirdsBoardGameEngine.sln  

jobs:
  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      solution_file: *solution

  build:
    uses: ./.github/workflows/build.yml
    with:
      solution_file: *solution
      docker_build: false
    needs:
      - static-analysis  

  tests:
    uses: ./.github/workflows/tests.yml
    with:
      solution_file: *solution
      run_component: true
      run_integration: false
      run_playwright: false      
    needs:
      - build

  compute_version:
    uses: ./.github/workflows/version.yml
    with:
      pr_title: ${{ github.event.pull_request.title || github.event.head_commit.message }}
    needs:
      - tests
      