name: Deploy

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      environment:
        required: true
        type: string
    outputs:
      deployment_uri:
        description: The URI of the deployed application
        value: ${{ jobs.deploy.outputs.deployment_uri }}
    secrets:
      azure_credentials:
        required: true
      pulumi_access_token:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: infra/Pulumi/AzureDev
    outputs:
      deployment_uri: ${{ steps.get-uri.outputs.deployment_uri }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Set up Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh
          echo "$HOME/.pulumi/bin" >> "$GITHUB_PATH"

      - name: Select Pulumi stack
        run: pulumi stack select ${{ inputs.environment }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi_access_token }}

      - name: Deploy to Azure
        run: |
          pulumi up --yes --stack ${{ inputs.environment }} \
            -c "image=${{ inputs.image_name }}:${{ inputs.image_tag }}"
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi_access_token }}

      - name: Get Deployment URI
        id: get-uri
        run: |
          # Fetch the deployment URI from Pulumi stack output
          DEPLOYMENT_URI=$(pulumi stack output deploymentUri)
          echo "deployment_uri=$DEPLOYMENT_URI" >> $GITHUB_OUTPUT
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.pulumi_access_token }}
