name: Publish .NET Package (resuable)

on:
  workflow_call:
    inputs:
      project_path:
        description: "Path to the .csproj"
        required: true
        type: string
      package_version:
        description: "Base SemVer version from csproj"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ inputs.package_version != '' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Restore
        run: dotnet restore "${{ inputs.project_path }}"

      - name: Pack
        run: |
          dotnet pack "${{ inputs.project_path }}" \
            -c Release \
            -p:PackageVersion=${{ inputs.package_version }} \
            -o ./artifacts

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key "${{ github.token }}" \
            --skip-duplicate