name: Publish Docker Image (Reusable)

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
      version:
        type: string
        required: true
      push_latest:
        type: boolean
        default: false
    outputs:
      image_tag:
        description: The tag of the published Docker image
        value: ${{ jobs.publish.outputs.image_tag }}
    secrets:
      registry_token:
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.publish.outputs.image_tag }}
    
    steps:
      - uses: actions/checkout@v6

      - name: Download Docker image artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.image_name }}-image

      - name: Load Docker image
        run: docker load -i ${{ inputs.image_name }}.tar

      - name: Docker Login GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.registry_token || github.token }}

      - name: Tag Image
        run: |
          IMAGE="${{ inputs.image_name }}"
          VERSION="${{ inputs.version }}"
          SHA_TAG="sha-${GITHUB_SHA::7}"

          OWNER="${{ github.repository_owner }}"
          OWNER="${OWNER,,}"   # LOWERCASE here
          GHCR="ghcr.io/$OWNER/$IMAGE"

          docker tag "$IMAGE:$SHA_TAG" "$GHCR:$VERSION"
          docker tag "$IMAGE:$SHA_TAG" "$GHCR:$SHA_TAG"

          if [ "${{ inputs.push_latest }}" = "true" ]; then
            docker tag "$IMAGE:$SHA_TAG" "$GHCR:latest"
          fi

      - name: Push Image
        id: publish
        run: |
          IMAGE="${{ inputs.image_name }}"
          VERSION="${{ inputs.version }}"
          SHA_TAG="sha-${GITHUB_SHA::7}"
          OWNER="${{ github.repository_owner }}"
          OWNER="${OWNER,,}"   # LOWERCASE here
          GHCR="ghcr.io/$OWNER/$IMAGE"

          docker push "$GHCR:$VERSION"
          docker push "$GHCR:$SHA_TAG"

          if [ "${{ inputs.push_latest }}" = "true" ]; then
            docker push "$GHCR:latest"
          fi

          echo "image_tag=$VERSION" >> $GITHUB_OUTPUT


